#! /bin/sh

FONT1="-misc-stlarch-medium-r-normal--10-100-75-75-c-80-iso10646-1"
FONT2="-gohu-gohufont-medium-r-normal--11-80-100-100-c-60-iso10646-1"
BACKGROUND="#e0171a1f"
FOREGROUND="#ff839496"
LINEHEIGHT="0"
EDGE_GAP=0
HEIGHT=14
WIDTH=$((`bspc query -T | head -n1 | cut -d" " -f2 | cut -d"x" -f1` - ($EDGE_GAP * 2)))
GEOMETRY="${WIDTH}x$HEIGHT+$EDGE_GAP+$EDGE_GAP"
MONITOR="$(bspc query -M | tail -n1)"

cd $(dirname $0)

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

bspc control --subscribe > "$PANEL_FIFO" &
#xtitle -sf 'T%s' > "$PANEL_FIFO" &
#clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &
#echo "T" >  "$PANEL_FIFO" &
#conky -c ./panel_conky > "$PANEL_FIFO" &
# easter eggs
sep_m="%{F#ffac6a76}  %{F-}"
sep_v="%{F#ffac6a76}  %{F-}"
sep_d="%{F#ffac6a76}  %{F-}"
sep_c="%{F#ffac6a76}  %{F-}"

while true; do
    echo "T" > "$PANEL_FIFO"

    date_min="$(date +'%H:%M')"
    vol="$(amixer get Master | tail -1 | egrep -o "[0-9]+%")"
    #vol="50"

    if [ -z "$nowplaying" ] ; then
        nowplaying="nanimo"
    fi

    echo "S" "$sep_m%{F#ffedeff2} $nowplaying $sep_v%{F#ffedeff2} $vol $sep_d%{F#ffedeff2} $date_min %{F-}" > "$PANEL_FIFO"

    sleep 1
done &

cat "$PANEL_FIFO" | ./panel_bar | bar -f "$FONT1","$FONT2" -F "$FOREGROUND" -B "$BACKGROUND" -g "$GEOMETRY" -u $LINEHEIGHT &

wait
