#!/bin/zsh

. panel_colors
. panel_config

# check if panel is already running
if [[ $(pgrep -cx panel) -gt 1 ]]; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

# exit gracefully if terminated
trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# remove old panel fifo, create new one
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

# desktops
while true; do
    echo -e "W%{A:session_menu.sh:}\ue812%{A}"
    sleep 3600;
done > "$PANEL_FIFO" &

# clock
while true; do
    echo -e "TIME$(date +"%H:%M") "
    sleep 30;
done > "$PANEL_FIFO" &

while true; do
    BT_ICON="\ue825"
    echo -e "B%{A:blueman-manager:}$BT_ICON%{A}"
    sleep 3600;
done > "$PANEL_FIFO" &

while true; do
    ALSA_STATE=$(amixer get Master | tail -1 | cut -d '[' -f 3 | sed 's/].*//g')
    ALSA_VOLUME=$(amixer get Master | tail -1 | cut -d '[' -f 2 | sed 's/\%].*//g')

    if [ $ALSA_VOLUME -gt 0 ] && [ "$ALSA_STATE" = "on" ]; then
        VOLUME_ICON='\ue850'
    elif [ $ALSA_VOLUME -eq 0 ] && ["$ALSA_STATE" = "on" ]; then
        VOLUME_ICON='\ue845'
    else
        VOLUME_ICON='\ue845'
    fi
    # uncomment next and delte the line after that to see volume percentage
    #echo -e V$VOLUME_ICON $ALSA_VOLUME
    echo -e "V%{A:pavucontrol:}$VOLUME_ICON%{A}"

    sleep 1
done > "$PANEL_FIFO" &

# static tray items
while true; do
    SEARCH_ICON='\ue837'
    NOTIFY_ICON='\ue815'
    echo -e "S%{A:my_menu.sh:}$SEARCH_ICON%{A}  %{A:xdotool key --clearmodifiers ctrl+shift+space:}$NOTIFY_ICON%{A}"
    sleep 3600;
done > "$PANEL_FIFO" &

# sound

panel_bar < "$PANEL_FIFO" | lemonbar -g x"$PANEL_HEIGHT" -f "$PANEL_FONT" -f "$ICON_FONT1" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" -o -0 | zsh &

wait
